(async function(){
'use strict';
const app=window.StudioApp;if(!app)return;if(!await app.ready){document.getElementById('accountStatus').textContent='Die Anmeldung benötigt den lokalen Speicher. Bitte zuerst den angezeigten Speicherfehler beheben.';document.getElementById('authForm').querySelectorAll('input,button').forEach(e=>e.disabled=true);return}const store=app.store,el=id=>document.getElementById(id),cfg=window.HAND_CONFIG||{};
const say=(s,error=false)=>{el('accountStatus').textContent=s;el('accountStatus').classList.toggle('error',error)};
let client,user=null,timer,busy=false,generation=0,switching=Promise.resolve();
try{if(!cfg.supabaseUrl||!cfg.supabasePublishableKey)throw Error('Konten sind noch nicht eingerichtet. Die Website funktioniert lokal. Zur Aktivierung bitte KONTO-EINRICHTEN.md befolgen.');const url=new URL(cfg.supabaseUrl);if(url.protocol!=='https:')throw Error('Die Konto-Adresse muss HTTPS verwenden.');const key=cfg.supabasePublishableKey;if(key.startsWith('sb_secret_'))throw Error('Nur den öffentlichen Publishable-Key verwenden.');if(key.split('.').length===3&&JSON.parse(atob(key.split('.')[1].replace(/-/g,'+').replace(/_/g,'/'))).role==='service_role')throw Error('Service-Role-Schlüssel sind hier nicht erlaubt.');client=supabase.createClient(url.href,key)}catch(e){say(e.message);el('authForm').querySelectorAll('input,button').forEach(e=>e.disabled=true);return}
function schedule(){clearTimeout(timer);if(user&&!busy)timer=setTimeout(sync,1800)}store.onChange=schedule;
function events(){return store.events.filter(app.validRecord)}
function checked(payload){if(!payload||!Array.isArray(payload.events)||payload.events.length>12000||payload.events.some(e=>!HandStorage.validEvent(e)||!app.validRecord(e)))throw Error('Unbekannte Kontodaten. Bitte Backup sichern und Support kontaktieren.');return payload.events}
function conflicts(){el('syncConflicts').replaceChildren();for(const group of store.conflicts().filter(g=>app.validRecord(g[0]))){const box=document.createElement('div');box.className='conflict-row';const label=document.createElement('p');label.textContent='Auf zwei Geräten geändert: '+group[0].key+'. Bitte eine Version wählen.';box.append(label);group.forEach((e,i)=>{const b=document.createElement('button');b.className='button';b.textContent='Version '+(i+1)+' · '+new Date(e.createdAt).toLocaleString();b.onclick=()=>{store.set(e.key,e.value);store.set('resolved:'+e.key+':'+(e.parent||'root'),true);app.hydrate();conflicts();schedule()};box.append(b)});el('syncConflicts').append(box)}}
async function sync(){if(!user||busy)return;if(app.isDrawing()){schedule();return}if(!navigator.onLine){say('Offline. Änderungen bleiben auf diesem Gerät und werden später synchronisiert.');return}busy=true;const epoch=generation,uid=user.id,scope=store.scope;const current=()=>epoch===generation&&store.scope===scope;try{app.persist();await store.queue;const {data,error}=await client.from('handwriting_states').select('revision,payload').eq('user_id',uid).maybeSingle();if(error)throw error;if(!current())return;let remote=data||{revision:0,payload:{events:[]}};for(let attempt=0;attempt<4;attempt++){if(app.isDrawing()){schedule();return}app.persist();await store.merge(checked(remote.payload));if(!current()||app.isDrawing())return;app.persist();app.hydrate();conflicts();const payload={events:events()};if(JSON.stringify(payload.events.map(e=>e.id).sort())===JSON.stringify(remote.payload.events.map(e=>e.id).sort()))break;const result=await client.rpc('save_handwriting',{expected_revision:remote.revision,new_payload:payload});if(result.error)throw result.error;if(!current())return;if(result.data.ok)break;remote=result.data;if(attempt===3)throw Error('Gleichzeitige Änderungen. Bitte erneut synchronisieren.')}say('Mit deinem Konto synchronisiert.');el('onlineStatus').textContent='Konto gespeichert'}catch(e){if(current())say('Synchronisierung nicht abgeschlossen: '+e.message+' Die Daten bleiben lokal gespeichert.',true)}finally{busy=false}}
async function session(session){generation++;clearTimeout(timer);const workspace=document.querySelector('.workspace');workspace.inert=true;document.activeElement?.blur();app.lockDraw();app.persist();await store.queue;user=session?.user||null;await store.switchScope(user?'account:'+new URL(cfg.supabaseUrl).origin+':'+user.id:'local');app.hydrate();workspace.inert=false;el('authForm').hidden=!!user;el('authHint').hidden=!!user;el('signedIn').hidden=!user;el('accountBadge').textContent=user?(user.email||'').split('@')[0]:'Auf allen Geräten weiterschreiben';el('onlineStatus').textContent=user?'Konto':'Lokal';say(user?'Angemeldet. Daten werden abgeglichen.':'Anmelden oder ein Konto erstellen.');if(user)schedule()}
function change(s){switching=switching.then(()=>session(s)).catch(e=>{document.querySelector('.workspace').inert=false;say('Kontowechsel fehlgeschlagen: '+e.message,true)})}
client.auth.onAuthStateChange((event,s)=>{if(event==='SIGNED_IN'||event==='SIGNED_OUT')setTimeout(()=>change(s),0)});
const initial=await client.auth.getSession();if(initial.error)say(initial.error.message,true);else await session(initial.data.session);
async function auth(create){const form=el('authForm');if(!form.reportValidity())return;const name=el('username').value.trim().toLowerCase(),password=el('password').value;if(!/^[a-z0-9_-]{3,24}$/.test(name)){say('Bitte einen gültigen Benutzernamen eingeben.',true);return}el('signIn').disabled=el('signUp').disabled=true;try{const credentials={email:name+'@users.handschrift.invalid',password};const result=create?await client.auth.signUp(credentials):await client.auth.signInWithPassword(credentials);if(result.error)throw result.error;el('password').value='';if(!result.data.session)say('Die E-Mail-Bestätigung muss im Supabase-Projekt deaktiviert werden, bevor dieses Konto nutzbar ist.',true)}catch(e){say('Anmeldung nicht abgeschlossen: '+e.message,true)}finally{el('signIn').disabled=el('signUp').disabled=false}}
el('authForm').onsubmit=e=>{e.preventDefault();auth(false)};el('signUp').onclick=()=>auth(true);el('syncNow').onclick=sync;
el('signOut').onclick=async()=>{const{error}=await client.auth.signOut({scope:'local'});if(error)say(error.message,true)};
el('takeLocal').onclick=async()=>{try{const local=await store.getDB('workspaces','local');for(const e of HandStorage.project(local||[]).values())if(app.validRecord(e)&&!e.key.startsWith('resolved:'))store.set(e.key,e.value);await store.queue;app.hydrate();schedule()}catch(e){say(e.message,true)}};
window.addEventListener('online',schedule);setInterval(()=>{if(!document.hidden)schedule()},30000);
})();
