/* Small vector PDF writer: ink paths stay sharp at any zoom level. */
(function(root){'use strict';
const enc=new TextEncoder(),n=x=>{if(!Number.isFinite(x))throw Error('Ungültige PDF-Koordinate.');return (+x.toFixed(3)).toString()},rgb=hex=>[1,3,5].map(i=>n(parseInt(hex.slice(i,i+2),16)/255)).join(' ');
const escape=s=>String(s).replace(/[^\x20-\x7e]/g,c=>({'ä':'ae','ö':'oe','ü':'ue','Ä':'Ae','Ö':'Oe','Ü':'Ue','ß':'ss','€':'EUR','–':'-','„':'"','“':'"'}[c]||'?')).replace(/[\\()]/g,'\\$&');
function ink(ss,transform,width,color){let out=`${rgb(color)} RG ${rgb(color)} rg ${n(width)} w 1 J 1 j\n`;for(const path of ss){if(!path.length)continue;const c=InkGeometry.curve(path),start=transform(...c.start);out+=`${n(start[0])} ${n(start[1])} m\n`;let prev=start;if(!c.segments.length)out+=`${n(start[0]+.01)} ${n(start[1])} l\n`;for(const q of c.segments){const ctrl=transform(q[0],q[1]),end=transform(q[2],q[3]);const a=prev.map((p,i)=>p+2*(ctrl[i]-p)/3),b=end.map((p,i)=>p+2*(ctrl[i]-p)/3);out+=`${[...a,...b,...end].map(n).join(' ')} c\n`;prev=end}out+='S\n'}return out}
function label(text,x,y,size=10,color='#617467'){return `BT /F1 ${size} Tf ${rgb(color)} rg 1 0 0 -1 ${n(x)} ${n(y)} Tm (${escape(text)}) Tj ET\n`}
function build(pages){if(!pages.length||pages.length>200)throw Error('PDF erlaubt maximal 200 Seiten.');const objs=[],add=s=>(objs.push(s),objs.length);add('<< /Type /Catalog /Pages 2 0 R >>');add('');const font=add('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'),kids=[];
for(const body of pages){const content='q 1 0 0 -1 0 842 cm\n'+body+'Q\n',cid=add(`<< /Length ${enc.encode(content).length} >>\nstream\n${content}endstream`),pid=add(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 ${font} 0 R >> >> /Contents ${cid} 0 R >>`);kids.push(`${pid} 0 R`)}objs[1]=`<< /Type /Pages /Kids [${kids.join(' ')}] /Count ${kids.length} >>`;
let pdf='%PDF-1.7\n',offsets=[0];for(let i=0;i<objs.length;i++){offsets.push(enc.encode(pdf).length);pdf+=`${i+1} 0 obj\n${objs[i]}\nendobj\n`}const pos=enc.encode(pdf).length;pdf+=`xref\n0 ${objs.length+1}\n0000000000 65535 f \n${offsets.slice(1).map(x=>String(x).padStart(10,'0')+' 00000 n \n').join('')}trailer\n<< /Size ${objs.length+1} /Root 1 0 R >>\nstartxref\n${pos}\n%%EOF`;return new Blob([enc.encode(pdf)],{type:'application/pdf'})}
function text({pages,factor,line,paper,color}){let count=0;return build(pages.map(items=>{let out='1 1 1 rg 0 0 595 842 re f\n';if(paper!=='blank'){out+='0.863 0.898 0.945 RG 0.65 w\n';const step=paper==='grid'?20:line;for(let y=paper==='grid'?40:60;y<810;y+=step)out+=`30 ${n(y)} m 565 ${n(y)} l S\n`;if(paper==='grid')for(let x=30;x<570;x+=20)out+=`${x} 40 m ${x} 820 l S\n`}for(const item of items){if(item.g.missing)throw Error('Bitte fehlende Zeichen zuerst zeichnen.');for(const p of item.g.ss){count+=p.length;if(count>1500000)throw Error('Text zu groß. Bitte aufteilen.')}out+=ink(item.g.ss,(x,y)=>[item.x+(x-item.g.b.min)*factor,item.y+(y-175)*factor],3.2*factor,color)}return out}))}
function specimen(glyphs){const entries=Object.entries(glyphs).filter(([,s])=>s.some(Boolean));if(!entries.length)throw Error('Zeichne zuerst mindestens einen Buchstaben.');const pages=[];let out='',row=0,page=0;
function begin(){page++;out='1 1 1 rg 0 0 595 842 re f\n'+label('MEINE HANDSCHRIFT',38,44,9)+label('Ein kleines Schriftportrait.',38,80,24,'#2b493a')+label('Deine gespeicherten Buchstaben und ihre Varianten',38,106,10)+label('Handschrift Studio / Seite '+page,38,811,9);row=0}
begin();for(const [char,samples]of entries){if(row===9){pages.push(out);begin()}const y=133+row*72;out+=label(char,38,y+37,13,'#2b493a');for(let i=0;i<10;i++){const x=76+i*47;out+='0.93 0.95 0.91 rg '+`${x} ${y} 44 61 re f\n`;out+=label(String(i+1),x+4,y+11,6);if(samples[i]){const ss=samples[i].map(InkGeometry.prepare);let left=Infinity,right=-Infinity,top=Infinity,bottom=-Infinity;for(const s of ss)for(const p of s){left=Math.min(left,p[0]);right=Math.max(right,p[0]);top=Math.min(top,p[1]);bottom=Math.max(bottom,p[1])}const scale=Math.min(1,34/Math.max(1,right-left),37/Math.max(1,bottom-top));out+=ink(ss,(a,b)=>[x+22+(a-(left+right)/2)*scale,y+36+(b-(top+bottom)/2)*scale],Math.max(.65,3.2*scale),'#315e50')}}row++}pages.push(out);return build(pages)}
root.StudioPDF={text,specimen};
})(globalThis);
